-- MCDA Lab: esquema para o Supabase (PostgreSQL).
-- Rodar uma vez no SQL Editor do painel do Supabase. Pode ser rodado de novo sem erro.
--
-- Equivale ao mcda_lab.db (SQLite), com três diferenças deliberadas:
--   1. ids são bigint com identity (no SQLite eram INTEGER PRIMARY KEY autoincrementado);
--   2. created_at é timestamptz (no SQLite era TEXT com CURRENT_TIMESTAMP);
--   3. os relacionamentos, que no SQLite eram implícitos, viram chaves estrangeiras.
-- exercises.data continua TEXT: o app grava e lê o JSON como string.

create table if not exists public.users (
    id       bigint generated by default as identity primary key,
    email    text unique,
    name     text,
    password text
);

create table if not exists public.exercises (
    id          bigint generated by default as identity primary key,
    owner_id    bigint references public.users (id) on delete cascade,
    name        text,
    description text,
    method      text,
    code        text unique,
    data        text,
    created_at  timestamptz not null default now()
);

create table if not exists public.participants (
    exercise_id bigint not null references public.exercises (id) on delete cascade,
    user_id     bigint not null references public.users (id) on delete cascade,
    primary key (exercise_id, user_id)
);

create table if not exists public.sessions (
    token      text primary key,
    user_id    bigint references public.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists exercises_owner_id_idx    on public.exercises (owner_id);
create index if not exists participants_user_id_idx  on public.participants (user_id);
create index if not exists sessions_user_id_idx      on public.sessions (user_id);

-- Segurança: RLS ligado e nenhuma policy. As tabelas guardam hashes de senha e tokens
-- de sessão, então a chave pública (anon / publishable) não enxerga nada. Só a chave
-- secreta (service_role / secret), usada pelo app no servidor, passa pelo RLS.
alter table public.users        enable row level security;
alter table public.exercises    enable row level security;
alter table public.participants enable row level security;
alter table public.sessions     enable row level security;
